### ISSUE TITLE
Unable to install on RPi Bookworm

### ISSUE THREAD

**Issue by madmacks59** [Mausy5043/bluepy3#8]
I've been running Bluepy on several Bullseye based RPis for awhile. Recently I had to reformat the SD card on one of those Pis, and I decided to upgrade to Bookworm, as it's the latest Pi OS. All went well, except now I can't install Bluepy on the Pi. When I run the "normal" install process the OS throws an error...

sudo pip install bluepy3

results in: 
error: externally-managed-environment

 This environment is externally managed
    To install Python packages system-wide, try apt install python3-xyz, where xyz is the package you are trying to install.

So I try...

sudo apt install python3-bluepy3

and the response is...

E: Unable to locate package python3-bluepy3

Is there some trick to getting Bluepy (or Bluepy3) installed on Bookworm?

**Comment by Mausy5043** [comment]
Thanks for trying `bluepy3`. First of all: please [**never** use `sudo pip install` again](https://www.reddit.com/r/Python/comments/9p2tkq/stop_using_sudo_pip_install/).

Please try to install with `python -m pip install bluepy3` as per the installation instructions.  

If that doesn't work then consider that officially you should set-up a `venv` for your user and continu from there. But because you'll probably, just like me, find that a bit too much trouble you can override it by creating the file `~/.config/pip/pip.conf` containing:
```
[global]
break-system-packages = true
```
This will install all packages under `~/.local/` where they should be. And that should definitely work.

Also please make sure you installed the required development tools using `sudo apt-get install libglib2.0-dev libbluetooth-dev`.

**Comment by Mausy5043** [comment]
Assuming the issue is fixed.   
If you feel it is not resolved you are welcome to re-open the issue and add additional data / logs to support further investigations.
